CricketerStats/Controllers/CricketerController.cs
using CrickerStats.Services;
using CricketerStats.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CricketerStats.Controllers
{
    [Authorize]
    public class CricketerController : Controller
    {
        // GET: Cricketer
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CricketerService(userId);
            var model = service.GetCricketers();

            return View(model);

        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CricketerCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            var service = CreateCricketService();

            if (service.CreateCricketer(model))
            {
                TempData["SaveResult"] = "Your Cricketer was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Cricketer could not be created.");

            return View(model);

        }

        private CricketerService CreateCricketService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CricketerService(userId);
            return service;
        }


        public ActionResult Details(int id)
        {
            var svc = CreateCricketService();
            var model = svc.GetCricketerById(id);

            return View(model);
        }

        public ActionResult Edit(int id)

        {
            var service = CreateCricketService();
            var detail = service.GetCricketerById(id);
            var model =
                new CricketerEdit
                {
                    Name = detail.Name,
                    Country = detail.Country,
                    TotalRuns = detail.TotalRuns,
                    CricketerId = detail.CricketerId
                };
            return View(model);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CricketerEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.CricketerId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }


            var service = CreateCricketService();

            if (service.UpdateCricketer(model))
            {
                TempData["SaveResult"] = "Your Cricketer was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your Cricketer could not be updated.");
            return View(model);
        }



        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateCricketService();
            var model = svc.GetCricketerById(id);

            return View(model);
        }




        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateCricketService();

            service.DeleteCricketer(id);

            TempData["SaveResult"] = "Your note was deleted";

            return RedirectToAction("Index");



        }
    }
}

CricketerStats/Controllers/OneDayStatsController.cs
using CrickerStats.Services;
using CricketerStats.Data;
using CricketerStats.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CricketerStats.Controllers
{

    [Authorize]
    public class OneDayStatsController : Controller
    {

        // GET: Cricketer
        public ActionResult Index()
        {
            //var userId = Guid.Parse(User.Identity.GetUserId());
            //var service = new OneDayStatsServices(userId);
            //var model = service.GetOneDayStatsByCricketer(id);

            var service = CreateOneDayService();
            var model = service.GetOneDayStats();
            return View(model);

        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OneDayStatsCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            var service = CreateOneDayService();

            if (service.CreateOneDayStats(model))
            {
                //TempData["SaveResult"] = "Your Cricketer was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Cricketer could not be created.");

            return View(model);

        }

        private OneDayStatsServices CreateOneDayService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new OneDayStatsServices(userId);
            return service;
        }


        public ActionResult Details(int id)
        {
            var svc = CreateOneDayService();
            var model = svc.GetOneDayStatsByCricketer(id);

            return View(model);
        }

        public ActionResult Edit(int id)

        {
            var service = CreateOneDayService();
            var detail = service.GetOneDayStatsEditById(id);
            var model =
                new OneDayStatsEdit
                {
                    WicketOneDayInt = detail.WicketOneDayInt,
                    CenturyOneDayInt = detail.CenturyOneDayInt,
                    HatrickOneDayInt = detail.HatrickOneDayInt,
                    CricketerId = detail.CricketerId,
                    OneDayIntId = detail.OneDayIntId
                    
                   
                };
            return View(model);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, OneDayStatsEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.OneDayIntId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }


            var service = CreateOneDayService();

            if (service.UpdateOneDayStats(model))
            {
                TempData["SaveResult"] = "Your Cricketer was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your Cricketer could not be updated.");
            return View(model);
        }



        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateOneDayService();
            var model = svc.GetOneDayStatsEditById(id);

            return View(model);
        }




        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateOneDayService();

            service.DeleteOneDayStats(id);

            TempData["SaveResult"] = "Your note was deleted";

            return RedirectToAction("Index");

        }

    }
}

CricketerStats/Views/Cricketer/Create.cshtml
@model CricketerStats.Models.CricketerCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CricketerCreate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalRuns, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalRuns, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalRuns, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CricketerStats/Views/Cricketer/Delete.cshtml
@model CricketerStats.Models.CricketerDetails

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CricketerDetails</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalRuns)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalRuns)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CricketerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CricketerId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CricketerStats/Views/Cricketer/Details.cshtml
@model CricketerStats.Models.CricketerDetails

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CricketerDetails</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalRuns)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalRuns)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CricketerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CricketerId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CricketerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CricketerStats/Views/Cricketer/Edit.cshtml
@model CricketerStats.Models.CricketerEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    

    <h4>CricketerEdit</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CricketerId)

<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TotalRuns, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TotalRuns, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TotalRuns, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-info"/>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CricketerStats/Views/Cricketer/Index.cshtml
@model IEnumerable<CricketerStats.Models.CricketerList>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>



<body class="cricketer">

</body>



<p>
    @Html.ActionLink("Create New", "Create")
</p>

@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">


        @ViewBag.SaveResult
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CricketerId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
             <a href="@Url.Action("Index", "OneDayStats", new { id = item.CricketerId})" >@item.Name</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CricketerId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CricketerId }) |
                @Html.ActionLink("Details", "Details", new { id = item.CricketerId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CricketerId }) |
                @Html.ActionLink("Create", "Create", new { id = item.CricketerId }) |
            </td>
        </tr>
    }

</table>